POST http://localhost:5174/api/v1/produtos
Content-Type: application/json

{
    "name": "K-Swiss V8",
    "categoria": "Tênis",
    "oferta": "",
    "genero": "",
    "preco": "",
    "valor_com_desconto": "" 
}